// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----- //
// vsync //
// ----- //

#define vsync_wrap_target 1
#define vsync_wrap 12
#define vsync_pio_version 0

#define vsync_T1 31
#define vsync_T2 31
#define vsync_T3 31

static const uint16_t vsync_program_instructions[] = {
    0x98a0, //  0: pull   block           side 1
            //     .wrap_target
    0xf83f, //  1: set    x, 31           side 1
    0x38c2, //  2: wait   1 irq, 2        side 1
    0x1842, //  3: jmp    x--, 2          side 1
    0xf03f, //  4: set    x, 31           side 0
    0x30c2, //  5: wait   1 irq, 2        side 0
    0x1045, //  6: jmp    x--, 5          side 0
    0xf83f, //  7: set    x, 31           side 1
    0x38c2, //  8: wait   1 irq, 2        side 1
    0x1848, //  9: jmp    x--, 8          side 1
    0xb827, // 10: mov    x, osr          side 1
    0x38c2, // 11: wait   1 irq, 2        side 1
    0x184b, // 12: jmp    x--, 11         side 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program vsync_program = {
    .instructions = vsync_program_instructions,
    .length = 13,
    .origin = -1,
    .pio_version = vsync_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config vsync_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + vsync_wrap_target, offset + vsync_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

// ----- //
// hsync //
// ----- //

#define hsync_wrap_target 2
#define hsync_wrap 14
#define hsync_pio_version 0

#define hsync_T1 31
#define hsync_T2 31
#define hsync_T3 31

static const uint16_t hsync_program_instructions[] = {
    0x80a0, //  0: pull   block
    0xa047, //  1: mov    y, osr
            //     .wrap_target
    0xfc3f, //  2: set    x, 31           side 3
    0xb442, //  3: nop                    side 1
    0x1c43, //  4: jmp    x--, 3          side 3
    0xd402, //  5: irq    nowait 2        side 1
    0xf83f, //  6: set    x, 31           side 2
    0xb042, //  7: nop                    side 0
    0x1847, //  8: jmp    x--, 7          side 2
    0xf43f, //  9: set    x, 31           side 1
    0xbc42, // 10: nop                    side 3
    0x144a, // 11: jmp    x--, 10         side 1
    0xbc22, // 12: mov    x, y            side 3
    0xb442, // 13: nop                    side 1
    0x1c4d, // 14: jmp    x--, 13         side 3
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program hsync_program = {
    .instructions = hsync_program_instructions,
    .length = 15,
    .origin = -1,
    .pio_version = hsync_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config hsync_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + hsync_wrap_target, offset + hsync_wrap);
    sm_config_set_sideset(&c, 3, true, false);
    return c;
}
#endif

// --- //
// rgb //
// --- //

#define rgb_wrap_target 2
#define rgb_wrap 10
#define rgb_pio_version 0

static const uint16_t rgb_program_instructions[] = {
    0x80a0, //  0: pull   block
    0xa047, //  1: mov    y, osr
            //     .wrap_target
    0xa022, //  2: mov    x, y
    0x2024, //  3: wait   0 pin, 4
    0x20a4, //  4: wait   1 pin, 4
    0x80a0, //  5: pull   block
    0x2027, //  6: wait   0 pin, 7
    0x6010, //  7: out    pins, 16
    0x20a7, //  8: wait   1 pin, 7
    0x0045, //  9: jmp    x--, 5
    0xc000, // 10: irq    nowait 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program rgb_program = {
    .instructions = rgb_program_instructions,
    .length = 11,
    .origin = -1,
    .pio_version = rgb_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config rgb_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + rgb_wrap_target, offset + rgb_wrap);
    return c;
}
#endif

// ------ //
// rgb_de //
// ------ //

#define rgb_de_wrap_target 1
#define rgb_de_wrap 16
#define rgb_de_pio_version 0

#define rgb_de_T1 31
#define rgb_de_T2 31

static const uint16_t rgb_de_program_instructions[] = {
    0x90a0, //  0: pull   block           side 0
            //     .wrap_target
    0xb047, //  1: mov    y, osr          side 0
    0xf03f, //  2: set    x, 31           side 0
    0x3025, //  3: wait   0 pin, 5        side 0
    0x30a5, //  4: wait   1 pin, 5        side 0
    0x3026, //  5: wait   0 pin, 6        side 0
    0x30a6, //  6: wait   1 pin, 6        side 0
    0x1045, //  7: jmp    x--, 5          side 0
    0x3026, //  8: wait   0 pin, 6        side 0
    0x30a6, //  9: wait   1 pin, 6        side 0
    0xf03f, // 10: set    x, 31           side 0
    0x3027, // 11: wait   0 pin, 7        side 0
    0x30a7, // 12: wait   1 pin, 7        side 0
    0x104b, // 13: jmp    x--, 11         side 0
    0x30a7, // 14: wait   1 pin, 7        side 0
    0x38c0, // 15: wait   1 irq, 0        side 1
    0x1088, // 16: jmp    y--, 8          side 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program rgb_de_program = {
    .instructions = rgb_de_program_instructions,
    .length = 17,
    .origin = -1,
    .pio_version = rgb_de_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config rgb_de_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + rgb_de_wrap_target, offset + rgb_de_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

